name: OTA translations

on:
  workflow_dispatch:
  schedule:
    # Every day at 10:11 UTC
    - cron:  '11 10 * * *'

jobs:
  build-ota-translations:
    name: Build OTA translations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GNU gettext
      run: sudo apt-get install gettext

    - name: Install Crowdin CLI
      run: npm i -g @crowdin/cli

    - name: Download latest translations from Crowdin
      run: |
        echo 'api_token: "${{secrets.CROWDIN_PERSONAL_TOKEN}}"' >>crowdin.yaml
        crowdin download
        rm crowdin.yaml

    - name: Build OTA updates
      run: scripts/build-ota-translations.sh

    - name: Upload OTA updates
      run: |
        VERSION=$(sed -n -e 's/.*POEDIT_VERSION.* "\([0-9]*\)\.\([0-9]*\).*".*/\1.\2/p' src/version.h)
        echo "OTA version: $VERSION"
        curl --fail-with-body -F 'data=@ota-update.tar' -H "X-Api-Key: ${{secrets.OTA_API_KEY}}" "${{secrets.OTA_UPLOAD_ENDPOINT}}?version=${VERSION}"
