name: Build

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-20.04
    env:
      MAKEFLAGS: -j2
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init deps/json deps/pugixml
    - name: Install ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}
    - name: Add ccache to path
      run: echo "/usr/lib/ccache" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        sudo apt-get install \
            gettext \
            libexpat1-dev \
            libdb++-dev \
            libboost-dev \
            libboost-system-dev \
            libboost-regex-dev \
            libboost-thread-dev \
            libboost-iostreams-dev \
            liblucene++-dev \
            libicu-dev \
            libwxgtk3.0-gtk3-dev \
            libwxgtk-webview3.0-gtk3-dev \
            libgtk-3-dev \
            libgtkspell3-3-dev \
            libcld2-dev \
            libcpprest-dev \
            libsecret-1-dev
    - name: Run bootstrap
      run: ./bootstrap
    - name: Run configure
      run: ./configure
    - name: Run make distcheck
      run: make distcheck

  build-macos:
    name: Build on macOS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}
    - name: Install external dependencies
      run: brew bundle --file=macos/Brewfile
    - uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        workspace: Poedit2.xcworkspace
        scheme: Poedit
        parallelize-targets: true
        action: build
